SELECT * FROM "Alianza_SC"."cat_Equipos"
SELECT * FROM "Alianza_SC"."cat_TiposBebidas"
SELECT * FROM "Alianza_SC"."cat_Bebidas"
SELECT * FROM "Alianza_SC"."cat_Vendedor"
SELECT * FROM "Alianza_SC"."Ventas"
SELECT * FROM "Alianza_SC"."Detalle_Ventas"

INSERT INTO "Alianza_SC"."cat_Equipos" (num_equipo) VALUES ('EQUIPO UNO');
INSERT INTO "Alianza_SC"."cat_Equipos" (num_equipo) VALUES ('EQUIPO DOS');
INSERT INTO "Alianza_SC"."cat_Equipos" (num_equipo) VALUES ('EQUIPO TRES');
INSERT INTO "Alianza_SC"."cat_Equipos" (num_equipo) VALUES ('EQUIPO CUATRO');
INSERT INTO "Alianza_SC"."cat_Equipos" (num_equipo) VALUES ('EQUIPO CINCO');

INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('aguas');
INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('aperitivos');
INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('bebidas energeticas');
INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('brandys');
INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('cerveza');
INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('cremas');
INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('refresco');
INSERT INTO "Alianza_SC"."cat_TiposBebidas" (nom_tiposbebidas) VALUES ('vinos');

INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.B. ESP. PETILLANT BRUT',300,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.B. ESP. PROSECCO DI VALDOBBIADENE',348,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.B. ESP. RIUNITE',22,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.B. FRANCISCO UNDURRAGA SAUV. BLANC',112,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.B. FRONTERA CHARDONNAY',456,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.R. APALTAGUA GRAN VERANO CARMENERE',234,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.R. E & J GALLO WHITE ZINFANDEL',987,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.R. ESP. MARTINI ROSE',126,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.R. NOVALVA PINOT',409,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.T. APALTAGUA GRAN VERANO CABERNET',222,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.T. APALTAGUA GRAN VERANO CARMENERE',444,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.T. ARNEGUI JOVEN EST MADERA',234,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.T. ATALAYAS DE GOLBAN (14º)',123,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.T. BAREFOOT CABERNET',567,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('V.T. CONCHA Y TORO CABERNET RESERVADO',889,8);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('APER. CAMPARI BITTER (20º)',123,2);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('APER. CAMPARI BITTER (25º)',120,2);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('APER. DUBONET',122,2);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('APER. FERNET VALLET',115,2);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BEB. E. BLUE SHOT LAT',45,3);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BEB. E. BOMBA YELLOW',46,3);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BEB. E. RED BULL',34,3);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. ALMA DE MAGNO SOLERA G RVA',999,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. CARDENAL DE MENDOZA S/EST',1234,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. DON PEDRO CLASICO',1120,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. DON PEDRO GRAN RVA',156,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. DON PEDRO LICORERA',230,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. CARDENAL DE MENDOZA C/EST',543,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. PRESIDENTE EDIC 50A',674,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. SAN MARCOS 10 ESTRELLAS',123,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. TORRES 10',255,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. TORRES 20',278,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. TORRES 5',459,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('BDY. VIEJO VERGEL',600,4);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA SOL LIMON SAL LATA',15,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA TECATE LATA',15,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA SUPERIOR LATA',13,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA INDIO LATA',15,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA DUFF LATA',25,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA CORONA LATA',13,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA CORONITA BOTELLA',12,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA XX LAGER BOTELLA',35,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CERVEZA MODELO FAMILIAR',67,5);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. COCA-COLA',15,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. JARRITOS',18,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. SQUIRT',13,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. PEPSI-COLA',12,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. LULU',10,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. SIDRAL',11,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. PASCUAL',12,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('REF. YOLI',13,7);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('AGUA MEMBERS MARK',15,1);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('AGUA BONAFONT',18,1);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('AGUA PEÑAFIEL',19,1);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('AGUA CIEL',22,1);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('AGUA E-PURA',19,1);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('AGUA LOS VOLCANES',13,1);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA DE ALMENDRA ORENDAIN',567,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA DE COCO CALAHUA',345,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA DE WHISKY BAILEYS CARAMELO',298,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA H. VALLET DE CASSIS',120,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA TEQUILADOR DE CHOCOLATE',379,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA H. VALLET DE MANDARINA',480,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA DE WHISKY BAILEYS',128,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA DE TEQUILA QUITA PENAS',432,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA FLAMINGO DE CACAO OBSC',189,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA DE CASSIS DE DIJON SISCA',468,6);
INSERT INTO"Alianza_SC"."cat_Bebidas"(Nom_Bebida,Precio_bebida,Id_tipbebida) VALUES ('CREMA DE WHISKY GLENBAYS',424,6);


INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('LUIS','ROJAS','ABAD','2000/08/21','M',1,'ROAL000821');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ARMANDO','RUIZ','ABASOLO','1996/10/14','M',1,'RUAA961014');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ROGELIO','ZAMORA','ACATITLA','2003/02/18','M',1,'ZAAR030218');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('FANNY','HERNANDEZ','ALCANTARA','1999/03/21','F',5,'HEAF990321');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ROSA','ROBLES','ARREDONDO','2012/09/15','F',5,'ROAR120915');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ESTELA','CASAS','ARROLLO','1989/08/01','F',3,'CAAE890801');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('RUTH','PEREZ','BAEZA','1985/10/22','F',2,'PEBR851022');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('JUDITH','DIAZ','BOCANEGRA','1994/02/04','F',2,'DIBJ940204');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('FERNANDO','MEZA','CAJALES','2010/01/15','M',4,'MECF100115');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('SABELY','OVIEDO','CALDERON','2019/04/30','F',4,'OVCS190430');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('OMAR','DEL VALLE','CASAS','2011/05/26','M',4,'DECO110526');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('BRUNO','GONZALEZ','CASTILLO','2018/09/21','M',4,'GOCB180921');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ISABEL','DE LA O','CHEDRAUI','2020/11/16','F',1,'DECI201116');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ROXANA','MARTINEZ','COSILLO','1999/02/28','F',1,'MACR990228');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ALMA','PEREIRA','COSTILLA','2016/02/14','F',3,'PECA160214');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('MARGARITA','SUAREZ','CRUZ','2020/06/15','F',3,'SUCM200615');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('MIGUEL','GOMEZ','DE LA GARZA','2013/12/14','M',3,'GODM131214');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('AGUSTIN','LOPEZ','DE LA O','2005/08/29','M',3,'LODA050829');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ROMAN','RUSTRIAN','DEL VALLE','1999/07/23','M',3,'RUDR990723');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('LORETO','ROMERO','DIAZ','2012/12/16','M',2,'RODL121216');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('AUGUSTO','SALAS','ECHEVERRIA','2017/12/24','M',2,'SAEA171224');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('OCTAVIO','BOCANEGRA','ENSASTEGUI','1998/05/21','M',2,'BOEO980521');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('JIMENA','MACEDO','ERIVES','2000/05/05','F',2,'MAEJ000505');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('JESUS','MONROY','GODINEZ','2020/04/30','M',5,'MOGJ200430');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('JOHANA','MELLADO','GOMEZ','2011/11/11','F',5,'MEGJ111111');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ALPHA','NARANJO','GONZALEZ','2019/01/19','F',5,'NAGA190119');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('GILDA','JIMENEZ','GUARDADO','2020/12/12','F',5,'JIGG201212');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('HORACIO','SOLIZ','GUISA','2008/03/16','M',5,'SOGH080316');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('HOMERO','INFANTE','HERNANDEZ','2000/08/21','M',5,'INHH000821');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ADRIAN','GUISA','HURTADO','1996/10/14','M',5,'GUHA961014');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ESTEBAN','LEYVA','INFANTE','2003/02/18','M',3,'LEIE030218');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ENRIQUE','MORA','JIMENEZ','1999/03/21','M',5,'MOJE990321');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('CHRISTIAN','CASTILLO','JUAREZ','2012/09/15','M',4,'CAJC120915');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('EUSEBIO','VALDIVIA','LEYVA','1989/08/01','M',4,'VALE890801');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('OSCAR','SUAREZ','LOPEZ','1985/10/22','M',2,'SULO851022');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('CLARISA','GODINEZ','LOPEZ','1994/02/04','F',2,'GOLC940204');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('CARLOS','CAJALES','MACEDO','2010/01/15','M',2,'CAMC100115');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ARMANDO','ARREDONDO','MARTINEZ','2019/04/30','M',1,'ARMA190430');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ANTONIO','ARROLLO','MELLADO','2011/05/26','M',1,'ARMA110526');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ANGEL','GUARDADO','MEZA','2018/09/21','M',1,'GUMA180921');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ANGELICA','OSORIO','MONROY','2020/11/16','F',3,'OSMA201116');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ANGELINA','ACATITLA','MORA','1999/02/28','F',3,'ACMA990228');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('MOISES','CRUZ','NARANJO','2016/02/14','M',3,'CRNM160214');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ISAIAS','JUAREZ','OBRADOR','2020/06/15','M',1,'JUOI200615');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('JACK','DE LA GARZA','OSORIO','2013/12/14','M',1,'DEOJ131214');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('LUCAS','SORRENTO','OVIEDO','2005/08/29','M',1,'SOOL050829');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('MATIAS','ERIVES','PASARAN','1999/07/23','M',1,'ERPM990723');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('MATEO','CHEDRAUI','PEÑA','2012/12/16','M',1,'CHPM121216');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('PABLO','ABAD','PEREIRA','2017/12/24','M',2,'ABPP171224');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('JUAN','ABASOLO','PEREZ','1998/05/21','M',2,'ABPJ980521');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('JOSEFINA','ENSASTEGUI','RAMIREZ','2000/05/05','F',2,'ENRJ000505');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ROSARIO','SANSEN','RICO','2020/04/30','F',3,'SARR200430');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ANA','PASARAN','ROBLES','2011/11/11','F',3,'PARA111111');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('KAREN','RAMIREZ','ROJAS','2019/01/19','F',3,'RARK190119');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('BERTHA','SANTOLLO','ROMERO','2020/12/12','F',3,'SARB201212');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('LUCIA','BAEZA','RUIZ','2008/03/16','F',3,'BARL080316');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('YOLANDA','RICO','RUSTRIAN','2000/08/21','F',5,'RIRY000821');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('FRANCISCA','VALDEZ','SALAS','1996/10/14','F',5,'VASF961014');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('GILBERTO','VERGARA','SANSEN','2003/02/18','M',4,'VESG030218');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('AIDE','COSTILLA','SANTOLLO','1999/03/21','F',4,'COSA990321');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('LYSA','COSILLO','SOLIZ','2012/09/15','F',4,'COSL120915');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ELISA','ECHEVERRIA','SORRENTO','1989/08/01','F',4,'ECSE890801');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ELISABETH','LOPEZ','SUAREZ','1985/10/22','F',4,'LOSE851022');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ALISARIN','HURTADO','SUAREZ','1994/02/04','F',2,'HUSA940204');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('LIZ','PEÑA','VALDEZ','2010/01/15','F',2,'PEVL100115');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('ROMERO','OBRADOR','VALDIVIA','2019/04/30','M',2,'OBVR190430');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('NICACIO','CALDERON','VERGARA','2011/05/26','M',3,'CAVN110526');
INSERT INTO"Alianza_SC"."cat_Vendedor"(Nom_ven,Apa_ven,Ama_ven,FechaIngreso_ven,Sex_ven,Id_equipo,RFC_ven) VALUES ('IGNACIO','ALCANTARA','ZAMORA','2018/09/21','M',1,'ALZI180921');

INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','11:56:35',1);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','11:59:24',2);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:40:19',3);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:16:53',4);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','04:30:44',5);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','05:31:38',6);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','07:18:57',7);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','05:23:21',8);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','03:04:40',9);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','03:16:26',10);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:46:04',11);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','04:51:49',12);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:47:09',13);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:53:14',14);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','05:32:46',15);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','06:19:58',16);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:58:41',17);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:28:18',18);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','11:18:48',19);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','02:26:46',20);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:48:39',21);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:26:03',22);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','11:02:23',23);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','07:09:40',24);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:25:18',25);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:35:53',26);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:43:18',27);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','07:58:17',28);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','06:10:27',29);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','06:04:50',30);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','07:29:13',31);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:41:19',32);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','06:45:43',33);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','06:43:53',34);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:29:37',35);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:32:58',36);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','03:58:13',37);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','04:35:38',38);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','12:58:42',39);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','04:15:37',40);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','02:46:13',41);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:33:38',42);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','01:36:06',43);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:03:09',44);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:05:25',45);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','12:33:14',46);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','07:33:25',47);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','02:12:27',48);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','05:58:37',49);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','01:47:11',50);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','12:57:29',51);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:34:44',52);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','03:53:33',53);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','01:39:15',54);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:21:03',55);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','11:11:56',56);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','03:31:59',57);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','02:59:45',58);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','02:57:32',59);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','10:43:13',60);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','11:32:34',61);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','06:06:49',62);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:35:39',63);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','03:29:06',64);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','08:35:06',65);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','02:53:09',66);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','05:52:55',67);
INSERT INTO"Alianza_SC"."Ventas"(fecha_venta,hora_venta,Id_vendedor) VALUES ('2022/10/26','09:45:17',68);

INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (1,1,35);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (2,2,73);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (3,3,3465);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (4,4,686);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (5,5,165);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (6,6,419);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (7,7,12);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (8,8,783);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (9,9,31);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (10,10,45);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (11,11,90);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (12,12,280);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (13,13,224);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (14,14,49);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (15,15,98);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (16,16,479);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (17,17,70);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (18,18,62);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (19,19,85);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (20,20,19);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (21,21,21);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (22,22,46);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (23,23,19);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (24,24,37);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (25,25,80);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (26,26,310);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (27,27,388);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (28,28,1448);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (29,29,122);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (30,30,600);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (31,31,2318);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (32,32,3051);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (33,33,215);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (34,34,79);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (35,35,852);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (36,36,4989);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (37,37,2260);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (38,38,6584);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (39,39,36842);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (40,40,6045);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (41,41,71967);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (42,42,2392);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (43,43,12540);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (44,44,61157);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (45,45,470);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (46,46,652);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (47,47,8228);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (48,48,4747);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (49,49,79);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (50,50,790);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (51,51,61);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (52,52,550);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (53,53,404);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (54,54,40);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (55,55,38);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (56,56,47);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (57,57,92);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (58,58,8);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (59,59,28);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (60,60,8);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (61,61,71);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (62,62,4);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (63,63,3);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (64,64,22);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (65,65,69);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (66,66,45);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (67,67,182);
INSERT INTO"Alianza_SC"."Detalle_Ventas"(num_venta,id_prod,cantunidades) VALUES (68,68,208);
